Repository IllumiDesk/async-nbgrader, pull requests merged in 2021-11, with the labels that each got.

#13 Add linting, types, and docstrings
  .flake8
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  README.md
  async_nbgrader/__init__.py
  async_nbgrader/_version.py
  async_nbgrader/apps/__init__.py
  async_nbgrader/apps/async_nbgraderapp.py
  async_nbgrader/apps/exportapp.py
  async_nbgrader/handlers.py
  async_nbgrader/helpers.py
  async_nbgrader/plugins/__init__.py
  async_nbgrader/plugins/export.py
  async_nbgrader/scheduler.py
  async_nbgrader/tasks.py
  async_nbgrader/tests/__main__.py
  async_nbgrader/tests/conftest.py
  async_nbgrader/tests/test_formgrader.py
  dev-requirements.txt
  pyproject.toml
  setup.py
Labels: documentation, enhancement, refactor

#14 Release version 0.3.1
  README.md
  async_nbgrader/_version.py
Labels: documentation, release

#12 Add app to process argo messages
  async_nbgrader/apps/async_nbgraderapp.py
  async_nbgrader/apps/processmessageapp.py
  async_nbgrader/handlers.py
  async_nbgrader/helpers.py
  async_nbgrader/scheduler.py
  async_nbgrader/tasks.py
  async_nbgrader/tests/__init__.py
  async_nbgrader/tests/apps/files/submitted-changed.ipynb
  async_nbgrader/tests/apps/files/submitted-unchanged.ipynb
  async_nbgrader/tests/apps/test_processmessageapp.py
  async_nbgrader/tests/test_formgrader.py
  pytest.ini
  setup.py
Labels: enhancement
