Repository IllumiDesk/async-nbgrader, pull requests merged in 2021-06, with the labels that each got.

#2 Move autograding to background
  .gitignore
  .gitignore/.gitignore
  LICENSE
  README.md
  async_nbgrader/__init__.py
  async_nbgrader/_version.py
  async_nbgrader/handlers.py
  async_nbgrader/scheduler.py
  async_nbgrader/static/common.js
  async_nbgrader/tasks.py
  async_nbgrader/tests/__init__.py
  async_nbgrader/tests/__main__.py
  async_nbgrader/tests/conftest.py
  async_nbgrader/tests/test_formgrader.py
  dev-requirements.txt
  pytest.ini
  requirements.txt
  setup.py
Labels: enhancement

#3 Update README.md
  README.md
Labels: documentation

#5 fix: packaging of static assets
  MANIFEST.in
  async_nbgrader/__init__.py
  async_nbgrader/_version.py
  setup.py
Labels: bug
